[package]
name = "icp_crud_dapp_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.17.2"
ic-cdk-macros = "0.8.2"
ic-cdk-timers = "0.11.0"
candid = "0.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
